name: Basic CI

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show OS
        run: echo "Running on ${{ matrix.os }}"

      - name: Show Python Version
        run: python --version

      - name: Show Current Directory
        run: pwd

      - name: Show Files
        run: ls